### ISSUE TITLE
Error in Count.py

### ISSUE THREAD

**Issue by ferrasa** [wyang17/SQuIRE#13]
Hi @wyang17 ,

in line 1567 of Count.py has an issue  on "_genename_dict_"  : `	filter_tx(outgtf_ref, genename_dict,read_length,genecounts)`

Thank you,

**Comment by wyang17** [comment]
Thank you, can I get the Traceback error message? Thanks!

**Comment by cpacyna** [comment]
Here’s what I got, if you havent’ been able to log onto slack!

Traceback (most recent call last):
File "/users/cpacyna/miniconda3/envs/squire_git/bin/squire", line 11, in <module>
   load_entry_point('SQuIRE', 'console_scripts', 'squire')()
File "/users/cpacyna/SQuIRE/squire/cli.py", line 156, in main
   subargs.func(args = subargs)
File "/users/cpacyna/SQuIRE/squire/Count.py", line 1567, in main
   filter_tx(outgtf_ref, genename_dict,read_length,genecounts)
NameError: global name 'genename_dict' is not defined

Chloe Pacyna
Biophysics & History of Medicine
Johns Hopkins University | Class of 2019
919-840-8128

**Comment by ferrasa** [comment]
It's exactly this traceback that I got.

Thank you.

**Comment by ferrasa** [comment]
It's exactly the traceback that I got.

Thank you.
