### ISSUE TITLE
argument error

### ISSUE THREAD

**Issue by SalimMegat** [wyang17/SQuIRE#21]
Hi, 

I have been trying to run Fetch on my samples but I guess I must be doing something wrong in the argument.sh file. 
Could you provide an example on how to fill out the argument file especially the sample names ? I keep getting "command not found" at the line 14 of the argument.sh file. Sorry, for that I am pretty new in the programming field but I find your tool pretty interesting for what I am doing. 

best, 

Salim.

**Comment by cpacyna** [comment]
Hi Salim,

Thanks for reaching out!  I want to clarify that Fetch doesn't actually run on your samples — it's a preliminary step that only needs to be done once as it downloads RefGene and builds the STAR index.  Fetch and Clean are both preparatory steps before Map and Count .

As for the arguments file, I did see an error in samplenames on line (line 14) in arguments.sh; your list of sample names should be a comma separated, not space separated as instructed in the comment.  I've fixed that and uploaded a "sample_arguments.sh" script to the sample_scripts folder in the SQuIRE repo.  Hopefully that fixes the error you're getting!  If not, let me know and we can troubleshoot further.

Regards,
Chloe

**Comment by SalimMegat** [comment]
HI Chloe, 

Thanks for your quick reply. I actually figured now that it was only meant to build the index since I was able to run it by calling Fetch.py on the command line just as follows: 

Fetch.py -b mm10 -o output folder -r -x -f 

However, while no errors seems to show up I do not think that the script is running .How long is it supposed to take with the options above ? 

Thanks for the fix ! 

Salim.

**Comment by cpacyna** [comment]
Hi Salim,

Fetch can take a longer time depending on your computer's/wifi's download speed and how large of a genome you're working with.  For me, fetch for hg19 on a compute cluster takes about 1.5 hours.  Even so, if you're running from the command line with Fetch.py you should see some output as Fetch runs if you use the verbosity option by including -v in the command.  Not sure if you changed this from the actual command you entered, but no spaces are allowed in folder names, so 'output folder' would need to be 'output_folder'.

Did you set up the miniconda environment as outlined in the installation step on the SQuIRE github README [page](https://github.com/wyang17/SQuIRE)?  It walks you through the required steps of getting the environment and dependencies set up.  It also will help you download all the necessary software.  Then, you can just type 'squire Fetch -b mm10 -o /your/output/folder/ -r -x -f -v' into your command line to reliably run anywhere once you've activated the environment by typing 'source activate squire'.  I'd recommend reading through and following along the readme installation.  If you have already, maybe some other issue is going on.

Regards,
Chloe

**Comment by SalimMegat** [comment]
Hi Chloe, 

Thank you for your feedback. I have bee following the instructions and while everything seemed to be fine in the first place, I’ve got multiple errors. First, the squire executable in ~/miniconda3/bin/ starts with the first line using the python in the miniconda3/bin direcotry which is Python3 by default. I changed the path to the python2.7 in the ~/miniconda3/envs/squire/bin directory. Is that ok to do ? 
Seconds, I’ve got the following error (see attached) saying pkg_resources.DistributionNotFound. I am quite confused now. Is is something that I missed during installation ? 

Many thanks, 

Salim

**Comment by cpacyna** [comment]
Hi Salim,

I have a few questions to help pinpoint what's going wrong.  What commands are causing the errors?  Is when you're running SQuIRE, or following the installation protocol?  You can check the status of the necessary software by entering the virtual environment "source activate squire" and typing "python" or "STAR" for each of the software listed on the installation protocol.  

Could you resend the second error log, along with the command that caused it?  I can't seem to find it on your comment, sorry.

Thanks!

Regards,
Chloe

**Comment by SalimMegat** [comment]
Hi Chloe, 

I had to reinstall everything and now it seems to work properly, at least the command squire Fetch. However with the command : squire Fetch -b 'mm10' -o squire_fetch -x -r -g -x -p 12 -v, downloading the Repeat Masker file takes quite some time. Is it normal ? (see below). Its been running for more than 30 min and the repeatmasker files is not downloaded yet ? Usually when I try to download the rmsk.file directly from UCSC it takes about a min. I am running the script on a server with 256 GB of RAM so I do not think that memory is the issue here. What do you think ? 

Thanks for your help ! 

Salim.

**Comment by cpacyna** [comment]
Hi Salim,

Sorry for the delay in response!  As long as you're allocating 12 threads on your cluster in addition to setting '-p 12', that command should work.  Are you getting any -v printout or error message?  What step is it getting "stuck" at?  Fetch can take a long time with option -x (which you have listed twice in the command!).  

Regards,
Chloe

**Comment by mb3188** [comment]
Hello, 
I am facing similar problem with fetch. I have installed conda environment without any errors, loaded the environment with source and tried to run fetch command which does not seem to exist (please see below). 
Then I simply used Fetch script to try to do the job but that did not report any errors but it did not fetched the files either. I'd appreciate any suggestions. 
Thanks, 
Martina

# installation verification  
Proceed ([y]/n)? y
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate squire
#
# To deactivate an active environment, use
#
#     $ conda deactivate



source activate squire

(squire) [mb998@cbsumezey01 MB998]$ squire Fetch
bash: squire: command not found...

(squire) [mb998@cbsumezey01 squire]$ python Fetch.py -b 'hg38'

**Comment by cpacyna** [comment]
Hi Martina,

Did you complete step 7 of installation, running the git clone command?

Regards,
Chloe

**Comment by mb3188** [comment]
Hi Chloe, 

Yes I did but I just realized I have probably done it outside of the conda environment, so fixed that. Now I can directly execute commands but I still do not get any data or any error from fetch command. It creates a folder but does not download any data. 

Thanks, 
Martina

**Comment by mb3188** [comment]
Thanks, I have solved the issue.
