### ISSUE TITLE
Run this tool in a custom genome?

### ISSUE THREAD

**Issue by acontrerasg** [wyang17/SQuIRE#49]
Hi there,

It seems that this tool is mainly though to use with already published genomes  and uses these fetch and clean in published  datasets before the mapping and counting, however I have a custom genome with a custom TE  _de novo_ annotation (together with an annotation made with maker)  and I was wondering If I could use this tool  and just fake the fetch and clean step or if I will face some incompatibilities in downstream analysis. 

Thank you!

**Comment by wyang17** [comment]
Yes, you can use a custom genome and skip the fetch and clean step as long as it's in the correct format - TE annotation in BED file, and gtf/STAR index for genome.
________________________________

**Comment by acontrerasg** [comment]
Thanks for the quick answer!
