### ISSUE TITLE
Problems with call output

### ISSUE THREAD

**Issue by fernandogs97** [wyang17/SQuIRE#58]
Hello, after performing some TE analysis in the mouse (analyzed against the mm39 version) I have obtained an erroneous call output in which several headers are missing, preventing the correct recognition of the data.
Anyone else has happened?
![imagen](https://user-images.githubusercontent.com/74077506/123331751-f8472480-d53f-11eb-8ab7-8df258143246.png)

**Comment by mars188** [comment]
Hi, 

Were you able to find an explanation for such an output? I obtained the similar output and not sure how to recognize the TE in this.

Please let me know.  Many thanks!

**Comment by fernandogs97** [comment]
Hello mars188, finally I noticed that the only think that you need to do is to move the headers 2 columns right for having the correct information, it is not a problem of squire, it also happen with deseq2 when you perform the differential expression analysis of genes. 
PD: The second column indicate the strand information if the data is stranded, as I perfomed the analysis with unstranded date its "." as it doesn't report that information.
