### ISSUE TITLE
Error while running Call step

### ISSUE THREAD

**Issue by AbhijeetRPatil** [wyang17/SQuIRE#60]
I am trying to run SquiRE call. However, I am getting errors. I have attached the error below. Could anyone please help me fix the error. 

Script Arguments
=================
count_folder=/home/arpatil/TE_counts
projectname=TEs_T1D_Normal_Squire
output_format=pdf
pthreads=12
call_folder=/home/arpatil/dete
condition2=Normal
table_only=False
group1=T1D_*
func=<function main at 0x7fa278b34140>
group2=Normal_*
subfamily=False
verbosity=True
condition1=T1D

Traceback (most recent call last):
  File "/home/arpatil/miniconda3/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/home/arpatil/Tools/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/home/arpatil/Tools/SQuIRE/squire/Call.py", line 286, in main
    create_TE_dict(TE_combo,TE_dict,threshold)
  File "/home/arpatil/Tools/SQuIRE/squire/Call.py", line 134, in create_TE_dict
    milliDiv = int(line[12])
ValueError: invalid literal for int() with base 10: 'Sample'

I tried editing Call.py line 134 by changing `milliDiv = int(line[12])` to `milliDiv = int(float(line[12]))`. However, I still keep getting error.

**Comment by fernandogs97** [comment]
> I am trying to run SquiRE call. However, I am getting errors. I have attached the error below. Could anyone please help me fix the error.
> # Script Arguments
> 
> count_folder=/home/arpatil/TE_counts
> projectname=TEs_T1D_Normal_Squire
> output_format=pdf
> pthreads=12
> call_folder=/home/arpatil/dete
> condition2=Normal
> table_only=False
> group1=T1D_*
> func=<function main at 0x7fa278b34140>
> group2=Normal_*
> subfamily=False
> verbosity=True
> condition1=T1D
> 
> Traceback (most recent call last):
> File "/home/arpatil/miniconda3/envs/squire/bin/squire", line 11, in
> load_entry_point('SQuIRE', 'console_scripts', 'squire')()
> File "/home/arpatil/Tools/SQuIRE/squire/cli.py", line 156, in main
> subargs.func(args = subargs)
> File "/home/arpatil/Tools/SQuIRE/squire/Call.py", line 286, in main
> create_TE_dict(TE_combo,TE_dict,threshold)
> File "/home/arpatil/Tools/SQuIRE/squire/Call.py", line 134, in create_TE_dict
> milliDiv = int(line[12])
> ValueError: invalid literal for int() with base 10: 'Sample'
> 
> I tried editing Call.py line 134 by changing `milliDiv = int(line[12])` to `milliDiv = int(float(line[12]))`. However, I still keep getting error.

Hello, Can you write here the code of Call that you have written in the bash?

**Comment by AbhijeetRPatil** [comment]
Hello, thanks for your response. 

`squire Call -i $CountDir -1 RNA_seq_T1D_* -2 RNA_seq_Normal_* -A T1D -B Normal -o ${deteDir} -p 4 -N TEs_T1D_Normal_Squire -f pdf -v`

The parameters for -1 and -2 are common patterns of case and control files.

**Comment by fernandogs97** [comment]
> Hello, thanks for your response.
> 
> `squire Call -i $CountDir -1 RNA_seq_T1D_* -2 RNA_seq_Normal_* -A T1D -B Normal -o ${deteDir} -p 4 -N TEs_T1D_Normal_Squire -f pdf -v`
> 
> The parameters for -1 and -2 are common patterns of case and control files.

I don't see any error, have you tried to perfome the call step without using the regular expression? Maybe it could be the reason of the error. (Just an idea)

**Comment by AbhijeetRPatil** [comment]
Can you please show me an example of how to use multiple files in the call step ?.

**Comment by imtiyazhariyani** [comment]
Hi there, I'm getting the same error and was wondering how you solved it? I see this error regardless of whether I use the regular expression or common patterns.
