### ISSUE TITLE
squire Call error

### ISSUE THREAD

**Issue by Surar** [wyang17/SQuIRE#78]
Hi,
Thank you very much for the useful software, I'm trying to run squire Call on my data and I'm getting different error messages like
ValueError: could not convert string to float: copies
or if I used -s option I'm getting the errors below:
ValueError: invalid literal for int() with base 10: 'tx_stop'
ValueError: invalid literal for int() with base 10: 'Sample'

however I'm still getting the deseq, MA-plots and the combo.txt output. do I need to worry about these error messages? if yes, what do you think might be the reason?

many thanks in advance.
Surar

**Comment by jamesc99** [comment]
Hi,

Actually, I don't know how to run Call command in SQuIRE, could anyone give me an example about it? I really appreciate that! (totally new to ComBio

Ryan

**Comment by Surar** [comment]
Hi @jamesc99, I'm not the author but I'm using SQUIRE.
There is an example of each command in the [README.md](https://github.com/wyang17/SQuIRE/blob/master/README.md) file of the code and for the squire call its 
squire Call [-h] -1 <str1,str2> or <str> -2 <str1,str2> or <str> -A -B [-o ] [-s] [-p ] [-N ] [-f ] [-v]
the options are explained in the README.md file.
if you have specific question feel free to ask.
Best regards
Surar

**Comment by Surar** [comment]
Hi all, 

the problem is solved by providing a basename shared for the samples in a specific condition and not a list for all of them.
